apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata: 
  name: cd-eventlistener
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - ref: cd-binding
      template:
        ref: cd-template