apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-task
spec:
  params:
    - name: echo-message
      type: string
      description: message to display in the echo message
  steps:
    - name: echo
      image: alpine:3
      command: [/bin/echo]
      args: ["msg:","$(params.echo-message)"]

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata: 
  name: checkout-task
spec:
  params:
    - name: repo-url
      description: repository URL clone
      type: string
    - name: branch
      description: branch to clone
      type: string
  steps:
    - name: checkout-step
      image: bitnami/git:latest
      command: [git]
      args: ["clone", "--branch", "$(params.branch)", "$(params.repo-url)"]
